/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Circulo_Rectangulo;

import java.util.Scanner;

/**
 *
 * @author tutu5
 */
public class circuloF extends javax.swing.JFrame {

    /**
     * Creates new form circuloF
     */
    public circuloF() {
        initComponents();
        
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_resultado = new javax.swing.JLabel();
        txt_radioC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_resultadoP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(209, 209, 209));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Circulo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Radio:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        txt_resultado.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        txt_resultado.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txt_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 180, 20));

        txt_radioC.setBackground(new java.awt.Color(209, 209, 209));
        txt_radioC.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        txt_radioC.setToolTipText("0");
        txt_radioC.setBorder(null);
        txt_radioC.setName(""); // NOI18N
        txt_radioC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_radioCKeyReleased(evt);
            }
        });
        jPanel2.add(txt_radioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 120, 20));

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Area:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Perimetro: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        txt_resultadoP.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        txt_resultadoP.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txt_resultadoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 180, 20));

        jLabel1.setBackground(new java.awt.Color(204, 0, 51));
        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Regresar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 410));

        setSize(new java.awt.Dimension(293, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public class Circulo implements FiguraGeometrica 
{
    private double radio;
    private double area;
    private double perimetro;
    static final double pi = 3.1415;
 
    public Circulo(double radio) 
    {
        this.radio = radio;
    }
 
    public double getRadio() 
    {
        return radio;
    }
 
    public void setRadio(double radio) 
    {
        this.radio = radio;
    }
 
    public double getAreaRadio() 
    {
        return area;
    }
 
    public double getPerimetro(){
        
        return perimetro;
        
    }
    @Override
    public void area() 
    {
        
        area = pi * radio * radio;
    }
    public void perimetro()
    {
        perimetro = 2 * pi * radio;
    }
}
    
    private void txt_radioCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_radioCKeyReleased
        
        
        double a;
        double perimetro;
        double resultado;
        
        a = doublevalidat(txt_radioC.getText());
        
        Circulo circulo = new Circulo(a);
        
        circulo.area();
        circulo.perimetro();
        
        resultado = circulo.getAreaRadio();
        perimetro = circulo.getPerimetro();
        
        txt_resultado.setText(String.valueOf(resultado));
        txt_resultadoP.setText(String.valueOf(perimetro));
        
                   
    }//GEN-LAST:event_txt_radioCKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Calcu Calcu = new Calcu();
        Calcu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    public double doublevalidat(String number){
        double result = 0;
        try{
            if (number !=null) {
                result = Double.parseDouble(number);
            }
            
        }catch(NumberFormatException nfe){
            //*No es numerico
        }
        return result;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(circuloF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(circuloF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(circuloF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(circuloF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new circuloF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_radioC;
    private javax.swing.JLabel txt_resultado;
    private javax.swing.JLabel txt_resultadoP;
    // End of variables declaration//GEN-END:variables
}
